### ISSUE TITLE
Awesome Theme

### ISSUE THREAD

**Issue by islanddog** [Siddy212/canvas-es-de#1]
Is it possible to flip the box art to the right and the game list to the left. This theme is beautiful but I'm so used to reading the games on the opposite side.

**Comment by Siddy212** [comment]
I just pushed an update to include "Flipped" variants of text list and detailed-grid :) Give it a try and see if that works for you!

**Comment by islanddog** [comment]
You are amazing and I'll try it later today. Thanks for all the work, it's awesome.

**Comment by islanddog** [comment]
Working! Your awesome.

**Comment by Siddy212** [comment]
Glad it's working for you!
