### ISSUE TITLE
Ultrawide mode?

### ISSUE THREAD

**Issue by Visnes** [Siddy212/canvas-es-de#2]
Would it be possible to add 21:9 for 3440x1440 sizes? It does work with auto, but the selection, among other elements, is now a little bit wider then they should be. 🙃

![image](https://github.com/user-attachments/assets/da004317-d8b4-4d7f-af50-b5ced3d2f4a9)

![image](https://github.com/user-attachments/assets/295ec5b4-ad95-4c16-ad10-634868ef01a8)

**Comment by Siddy212** [comment]
Now added! Try downloading and selecting 21:9 as the aspect ratio :)

**Comment by Visnes** [comment]
Worked like a charm! Thanks! 😃
